# Generated by Django 3.1.5 on 2021-01-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total sale')),
                ('date_sale', models.DateField(verbose_name='date sale')),
                ('is_active', models.BooleanField(default=True, help_text='Check if the sale is active', verbose_name='Sale active')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
            options={
                'ordering': ['-date_sale'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
