# Generated by Django 3.1.5 on 2021-01-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('stock', models.PositiveIntegerField(verbose_name='product stock')),
                ('is_auctioned', models.BooleanField(default=False, help_text='Check if the products have already been auctioned', verbose_name='Auctioned product')),
                ('is_active', models.BooleanField(default=True, help_text='Check if the products are available', verbose_name='Actived product')),
            ],
            options={
                'ordering': ['-name'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
